import { randomUUID } from 'node:crypto';
import { mkdir, readFile, rename, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { parse, stringify } from 'yaml';
import { z } from 'zod';
import type { VaultRegistry } from '../config/registry.js';
import { SecurityError } from '../security/path-security.js';
import type { FilesystemService } from './filesystem-service.js';
import {
  flattenProjectMapping,
  parseProjectMapping,
  type ProjectMapping,
  ProjectMappingService,
} from './project-mapping-service.js';

const projectConfigSchema = z.object({
  schemaVersion: z.literal(1),
  vault: z.string().trim().min(1),
  mappingFile: z.string().trim().min(1).default('mapping.yaml'),
});

export interface GeneratedProjectFile {
  path: string;
  action: 'created' | 'replaced' | 'preserved';
}

export interface ProjectMappingDiff {
  added: string[];
  removed: string[];
  changed: string[];
  unchanged: string[];
}

export interface ProjectBootstrapResult extends ProjectMappingDiff {
  projectPath: string;
  vault: string;
  files: GeneratedProjectFile[];
  detected: string[];
  missing: string[];
}

interface ProjectConfig {
  schemaVersion: 1;
  vault: string;
  mappingFile: string;
}

const generatedReadme = `# Obsidian local project configuration

This directory is generated by ObsidianConnector and is safe to commit.

- Edit \`mapping.yaml\` to change the documentation tree.
- Run the MCP tool \`sync_project_config\` after editing the mapping.
- The mapping changes retrieval configuration only. It does not create, move,
  rename, or delete notes in the vault.
- Machine-specific vault paths remain in the ignored \`config/vaults.json\`.
`;

function isMissing(error: unknown): boolean {
  return (
    (error instanceof SecurityError && error.code === 'NOT_FOUND') ||
    (error as NodeJS.ErrnoException | undefined)?.code === 'ENOENT'
  );
}

function projectConfigContent(vault: string): string {
  return `${JSON.stringify(
    {
      schemaVersion: 1,
      vault,
      mappingFile: 'mapping.yaml',
      retrieval: {
        mode: 'filesystem',
        bm25: false,
        pgvector: false,
        localEmbedder: false,
        reranker: false,
      },
    },
    null,
    2,
  )}\n`;
}

function mappingPath(projectRoot: string, relativePath: string): string {
  const resolved = path.resolve(projectRoot, relativePath);
  const relative = path.relative(projectRoot, resolved);
  if (
    path.isAbsolute(relative) ||
    relative === '..' ||
    relative.startsWith(`..${path.sep}`) ||
    path.basename(resolved) !== 'mapping.yaml'
  ) {
    throw new Error(
      'Project mapping file must be mapping.yaml inside the project',
    );
  }
  return resolved;
}

async function ensureDirectory(directory: string): Promise<void> {
  const info = await stat(directory).catch(() => undefined);
  if (info && !info.isDirectory())
    throw new Error('Project path is not a directory');
  if (!info) await mkdir(directory, { recursive: true });
}

async function writeGeneratedFile(
  directory: string,
  filename: string,
  content: string,
  overwrite: boolean,
): Promise<GeneratedProjectFile> {
  const target = path.join(directory, filename);
  const existing = await stat(target).catch(() => undefined);
  if (existing && !existing.isFile())
    throw new Error(`Generated project path is not a file: ${filename}`);
  if (existing && !overwrite) return { path: filename, action: 'preserved' };
  const temporary = `${target}.${randomUUID()}.tmp`;
  await writeFile(temporary, content, 'utf8');
  await rename(temporary, target);
  return { path: filename, action: existing ? 'replaced' : 'created' };
}

function diffMappings(
  before: Record<string, string>,
  after: Record<string, string>,
  prefix = '',
): ProjectMappingDiff {
  const keys = new Set([...Object.keys(before), ...Object.keys(after)]);
  const result: ProjectMappingDiff = {
    added: [],
    removed: [],
    changed: [],
    unchanged: [],
  };
  for (const key of [...keys].sort()) {
    const label = prefix ? `${prefix}:${key}` : key;
    if (!(key in before)) result.added.push(label);
    else if (!(key in after)) result.removed.push(label);
    else if (before[key] !== after[key]) result.changed.push(label);
    else result.unchanged.push(label);
  }
  return result;
}

function combineDiffs(
  roles: ProjectMappingDiff,
  aliases: ProjectMappingDiff,
): ProjectMappingDiff {
  return {
    added: [...roles.added, ...aliases.added],
    removed: [...roles.removed, ...aliases.removed],
    changed: [...roles.changed, ...aliases.changed],
    unchanged: [...roles.unchanged, ...aliases.unchanged],
  };
}

async function readProjectConfig(projectRoot: string): Promise<ProjectConfig> {
  const configPath = path.join(projectRoot, '.obsidian-local', 'config.json');
  const content = await readFile(configPath, 'utf8');
  const parsed = projectConfigSchema.parse(parse(content));
  mappingPath(projectRoot, parsed.mappingFile);
  return parsed;
}

export class ProjectBootstrapService {
  constructor(
    private readonly registry: VaultRegistry,
    private readonly mapping: ProjectMappingService,
    private readonly files: FilesystemService,
  ) {}

  private async detect(
    vault: string,
    projectMapping: ProjectMapping,
  ): Promise<{ detected: string[]; missing: string[] }> {
    const detected: string[] = [];
    const missing: string[] = [];
    for (const note of flattenProjectMapping(projectMapping).notes) {
      try {
        await this.files.readNote(vault, note.path);
        detected.push(note.path);
      } catch (error) {
        if (!isMissing(error)) throw error;
        missing.push(note.path);
      }
    }
    return { detected, missing };
  }

  async initialize(
    projectPath: string,
    vault: string,
    overwriteGenerated = true,
  ): Promise<ProjectBootstrapResult> {
    const projectRoot = path.resolve(projectPath);
    await ensureDirectory(projectRoot);
    this.registry.get(vault);
    const localDirectory = path.join(projectRoot, '.obsidian-local');
    await mkdir(localDirectory, { recursive: true });

    let projectMapping = await this.mapping.mappingForVault(vault);
    const existingMappingPath = path.join(localDirectory, 'mapping.yaml');
    if (!overwriteGenerated) {
      const existing = await readFile(existingMappingPath, 'utf8').catch(
        () => undefined,
      );
      if (existing) projectMapping = parseProjectMapping(existing);
    }
    if (projectMapping.vault !== vault)
      throw new Error(
        'Project mapping vault does not match the requested vault',
      );
    const flattened = flattenProjectMapping(projectMapping);
    const before = this.registry.get(vault).codebaseIndex;
    await this.registry.updateCodebaseIndex(vault, {
      roles: flattened.roles,
      aliases: flattened.aliases,
    });
    const detected = await this.detect(vault, projectMapping);
    const files = [
      await writeGeneratedFile(
        localDirectory,
        'config.json',
        projectConfigContent(vault),
        overwriteGenerated,
      ),
      await writeGeneratedFile(
        localDirectory,
        'mapping.yaml',
        stringify(projectMapping),
        overwriteGenerated,
      ),
      await writeGeneratedFile(
        localDirectory,
        'README.md',
        generatedReadme,
        overwriteGenerated,
      ),
    ];
    return {
      projectPath: projectRoot,
      vault,
      files,
      ...detected,
      ...combineDiffs(
        diffMappings(before.roles, flattened.roles),
        diffMappings(before.aliases, flattened.aliases, 'alias'),
      ),
    };
  }

  async sync(projectPath: string): Promise<ProjectBootstrapResult> {
    const projectRoot = path.resolve(projectPath);
    await ensureDirectory(projectRoot);
    const config = await readProjectConfig(projectRoot);
    const mappingFile = mappingPath(
      projectRoot,
      path.join('.obsidian-local', config.mappingFile),
    );
    const projectMapping = parseProjectMapping(
      await readFile(mappingFile, 'utf8'),
    );
    if (projectMapping.vault !== config.vault)
      throw new Error('Project mapping vault does not match project config');
    const before = this.registry.get(config.vault).codebaseIndex;
    const flattened = flattenProjectMapping(projectMapping);
    await this.registry.updateCodebaseIndex(config.vault, {
      roles: flattened.roles,
      aliases: flattened.aliases,
    });
    const detected = await this.detect(config.vault, projectMapping);
    return {
      projectPath: projectRoot,
      vault: config.vault,
      files: [],
      ...detected,
      ...combineDiffs(
        diffMappings(before.roles, flattened.roles),
        diffMappings(before.aliases, flattened.aliases, 'alias'),
      ),
    };
  }
}
